/** Every piece of text the player reads. Keep labels here so they can be translated later. */
export const STRINGS = {
  title: 'Starman Soccer',
  chooseCountry: 'Choose a country',
  vs: 'vs',
  controlsLine1: 'Arrows move   Z pass   X shoot',
  controlsLine2: 'C sprint   Space switch   X slide',
  credits: 'Created by Joaquim Prins | Designed and Implemented by Ricardo Prins with Grok',
  kickOff: 'Kick off!',
  goal: 'Goal!',
  save: 'Save!',
  throwIn: 'Throw in',
  corner: 'Corner',
  goalKick: 'Goal kick',
  freeKick: 'Free kick',
  penalty: 'Penalty!',
  foul: 'Foul!',
  yellowCard: 'Yellow card',
  sentOff: 'Sent off',
  blocked: 'Blocked!',
  fullTime: 'Full time',
  youWin: 'You win!',
  draw: 'Draw!',
  teamWins: (team: string) => `${team} wins`,
  pressEnterForMenu: 'Press Enter for menu',
  pressEnterToPlay: 'Enter to play',
  pressEnterToContinue: 'Enter to continue',
  pressEnterForPenalties: 'Enter for penalties',
  newCup: 'New cup',
  continueCup: 'Continue',
  groups: 'Groups',
  playedDiffPoints: 'Played, goal difference, points',
  moreGroups: 'Left right more',
  enterNext: 'Enter next',
  enterBack: 'Enter back',
  matchday: (n: number) => `Matchday ${n}`,
  roundOf16: 'Round of 16',
  quarterfinal: 'Quarterfinal',
  semifinal: 'Semifinal',
  final: 'Final',
  champions: 'Champions',
  eaglesOut: "Eagle's Ning are out",
  lastScore: 'Last',
  newCupAgain: 'Enter for a new cup',
  penalties: 'Penalties',
  aim: 'Aim',
  left: 'Left',
  center: 'Center',
  right: 'Right',
  shoot: 'X shoots',
  keeper: 'Keeper',
  kicks: 'Kicks',
  suddenDeath: 'Sudden death',
  arrowsAim: 'Arrows aim',
  sound: 'Sound',
  mute: 'Mute',
  playerLabel: (num: number, name: string) => `${num} ${name}`,
} as const;
